// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/devo': {
    params: {};
  };
  '/stars': {
    params: {};
  };
  '/fluids': {
    params: {};
  };
  '/sakuga': {
    params: {};
  };
  '/svafa': {
    params: {};
  };
  '/api/github': {
    params: {};
  };
  '/api/hackernews': {
    params: {};
  };
  '/api/image': {
    params: {};
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page: '/' | '/devo' | '/stars' | '/fluids' | '/sakuga' | '/svafa' | '/api/github' | '/api/hackernews' | '/api/image';
  };
  'routes/home.tsx': {
    id: 'routes/home';
    page: '/';
  };
  'routes/devo.tsx': {
    id: 'routes/devo';
    page: '/devo';
  };
  'routes/stars.tsx': {
    id: 'routes/stars';
    page: '/stars';
  };
  'routes/fluids.tsx': {
    id: 'routes/fluids';
    page: '/fluids';
  };
  'routes/sakuga.tsx': {
    id: 'routes/sakuga';
    page: '/sakuga';
  };
  'routes/svafa.tsx': {
    id: 'routes/svafa';
    page: '/svafa';
  };
  'routes/api.github.ts': {
    id: 'routes/api.github';
    page: '/api/github';
  };
  'routes/api.hackernews.ts': {
    id: 'routes/api.hackernews';
    page: '/api/hackernews';
  };
  'routes/api.image.ts': {
    id: 'routes/api.image';
    page: '/api/image';
  };
};

type RouteModules = {
  root: typeof import('./app/root.tsx');
  'routes/home': typeof import('./app/routes/home.tsx');
  'routes/devo': typeof import('./app/routes/devo.tsx');
  'routes/stars': typeof import('./app/routes/stars.tsx');
  'routes/fluids': typeof import('./app/routes/fluids.tsx');
  'routes/sakuga': typeof import('./app/routes/sakuga.tsx');
  'routes/svafa': typeof import('./app/routes/svafa.tsx');
  'routes/api.github': typeof import('./app/routes/api.github.ts');
  'routes/api.hackernews': typeof import('./app/routes/api.hackernews.ts');
  'routes/api.image': typeof import('./app/routes/api.image.ts');
};
